# Generated by Django 2.0 on 2018-01-01 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stravauth', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('goal_distance', models.FloatField()),
                ('club', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strava_club_challenge.Challenge')),
                ('participant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stravauth.StravaToken')),
            ],
        ),
    ]
