# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 13:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('stravauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('goal_distance', models.FloatField()),
                ('club', models.CharField(max_length=200)),
                ('participant',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stravauth.StravaToken')),
            ],
        ),
    ]
