# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:24
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stravauth', '0001_initial'),
        ('strava_club_challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='participant',
        ),
        migrations.AddField(
            model_name='participation',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strava_club_challenge.Challenge'),
        ),
        migrations.AddField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stravauth.StravaToken'),
        ),
    ]
