# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strava_club_challenge', '0002_auto_20170209_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='name',
            field=models.CharField(default='Random Challenge Name', max_length=300),
            preserve_default=False,
        ),
    ]
