# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('stravauth', '0001_initial'),
        ('strava_club_challenge', '0003_challenge_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StravaUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stravauth.StravaToken')),
            ],
        ),
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strava_club_challenge.StravaUser'),
        ),
    ]
