# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 21:02
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('strava_club_challenge', '0004_auto_20170227_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stravauser',
            name='token',
        ),
        migrations.AlterField(
            model_name='participation',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stravauth.StravaToken'),
        ),
        migrations.DeleteModel(
            name='StravaUser',
        ),
    ]
